### ISSUE TITLE
useCoins Button / useCoins Page

### ISSUE THREAD

**Issue by annaleaschroeder** [neuefische/qcoins-mvp#12]
Value statement - a requirement, not a solution

As a **user**

I need **a button**  "Spend Coins"

so that **I can navigate to the spending-UI**

## Acceptance criteria

- [x] add button on home-screen

- [x] add page where UI for using-coins will be located

- [x] add Routing to the use Button on the home-page. it leads to the useCoins Page

## Tasks

- [x] add feature branch

- [x] add button with routing

## Size

(small)

**Comment by janhenrikfock** [comment]
Since we have added the function to use our coins the names we have given the hook and the functions earlyer dont fit anymore. I would like to go through the code and change names of hook and props in order to make them indicative (semantically).
