### ISSUE TITLE
Settings for chart bars colors

### ISSUE THREAD

**Issue by mpagels** [neuefische/qcoins-mvp#16]
## Value statement - a requirement, not a solution
As a **user**
I need **the possibility to change the colors of grow/share/spend bars/elements**
so that **I can better differentiate the bars or customize the bars with my kids**

## Acceptance criteria
- [ ] three buttons (elements) for grow/share/spend
- [ ] when click/touch of one of button/element then opens a color picker for choosing the color
- [ ] a save button to save all settings
- [ ] (functional descriptions)

## Tasks
- [ ] (todos for the team)

## Size
(medium)
