### ISSUE TITLE
Input spending-options (parents)

### ISSUE THREAD

**Issue by annaleaschroeder** [neuefische/qcoins-mvp#20]
## Value statement - a requirement, not a solution

As a **user**

I need **to give my child options with different "price-tags**

so that **the child knows how spending in different accounts is going to influence their account balances**

## Acceptance criteria

- [ ] input for parents: What exactly can their child spend coins on, and how much does each spending option "cost" --> dropdown menue/...

- [ ] Input field to add options 

- [ ] add/delete/edit spending-options

## Tasks

- [ ] (todos for the team)

## Size

(small, medium, large)
