### ISSUE TITLE
Add Header+Graph to useCoins component

### ISSUE THREAD

**Issue by janhenrikfock** [neuefische/qcoins-mvp#21]
## Value statement - a requirement, not a solution
As a **user** 
I need **indicators how much coins are in my accounts** 
so that **i know how much i can spend** 

## Description (Text, Scribble, Wireframe, Design)

<img width="504" alt="Bildschirmfoto 2020-11-10 um 22 01 49" src="https://user-images.githubusercontent.com/67914612/98733221-7cc5a800-23a0-11eb-9edc-3bd58d5b524c.png">

## Acceptance criteria
- [ ] Add an indicative headline to the page.
- [x] the header component displays, how many coins are in each account.
- [x] The Graph gives a visual indicator of each account.
- [ ] add a confirm button to the page, that routes back to the landingpage. (Already exists in distribute-Coins component.

## Tasks
- [x] add the (already existing) header component to the useCoin component.
- [x] add the (already existing) graph component to the useCoin component.
- [ ] add an headline
- [x] add confirm button with routing back to landingpage

## Size
small
