### ISSUE TITLE
Using Coins from "Grow-Account"

### ISSUE THREAD

**Issue by janhenrikfock** [neuefische/qcoins-mvp#22]
## Value statement - a requirement, not a solution
As a **user** 
I need **a functioning UI in the useCoins component** 
so that **i can use the coins on my grow-account** 

## Description (Text, Scribble, Wireframe, Design)

<img width="435" alt="Bildschirmfoto 2020-11-10 um 22 08 50" src="https://user-images.githubusercontent.com/67914612/98733785-5b18f080-23a1-11eb-8d47-53fe69488eca.png">

## Acceptance criteria
- [x] add the distributeButton component to the page
- [x] write a useGrow function in the useEarnings hook.
- [x] use the useGrow function in the useCoins component to update Graph and number-Indicators in the header.
- [ ] users must not be allowed to spend more coins than they have in their grow-account.
- [ ] users must not be able to enter negative integers (which would increase the grow account)

## Tasks
- [x] add the distributeButton component
- [x] write useGrow function in useEarnings hook
- [x] use useGrow function in the distributeButton component to use coins on grow-account
- [ ] form validation on the value in the Button-component

## Size
large

**Comment by mpagels** [comment]
I dont't know if we need #23 & #24 ? For me is that one component which we can use again (for spend and share). The component needs only to know where to put the coins at end and that info can be "prop-able". ;-)

**Comment by janhenrikfock** [comment]
> I dont't know if we need #23 & #24 ? For me is that one component which we can use again (for spend and share). The component needs only to know where to put the coins at end and that info can be "prop-able". ;-)

Yeah i thought about that. I definitely think those issues are quite similar.
To me, this was the best way to split the userStory without making each issue too small. But its definitely up for discussion!

**Comment by janhenrikfock** [comment]
Since we have added the function to use our coins, the names we have given the hook and the functions earlyer dont fit anymore. I would like to go through the code and change names of hook and props in order to make them indicative (semantically).
