### ISSUE TITLE
Using Coins from "Share-Account"

### ISSUE THREAD

**Issue by janhenrikfock** [neuefische/qcoins-mvp#23]
## Value statement - a requirement, not a solution
As a **user** 
I need **a functioning UI in the useCoins component** 
so that **i can use the coins on my share-account** 

## Description (Text, Scribble, Wireframe, Design)

<img width="427" alt="Bildschirmfoto 2020-11-10 um 22 38 40" src="https://user-images.githubusercontent.com/67914612/98736857-ae8d3d80-23a5-11eb-828f-c4dd72b7d60d.png">

## Acceptance criteria
- [ ] add the distributeButton component to the page
- [ ] write a useShare function in the useEarnings hook.
- [ ] use the useShare function in the useCoins component to update Graph and number-Indicators in the header.
- [ ] users must not be allowed to spend more coins than they have in their grow-account.
- [ ] users must not be able to enter negative integers (which would increase the share-account)

## Tasks
- [ ] add the distributeButton component
- [ ] write useShare function in useEarnings hook
- [ ] use useShare function in the distributeButton component to use coins on share-account
- [ ] form validation on the value in the Button-component

## Size
large
