### ISSUE TITLE
Using Coins from "Spend-Account"

### ISSUE THREAD

**Issue by janhenrikfock** [neuefische/qcoins-mvp#24]
## Value statement - a requirement, not a solution
As a **user** 
I need **a functioning UI in the useCoins component** 
so that **i can use the coins on my share-account** 

## Description (Text, Scribble, Wireframe, Design)

<img width="421" alt="Bildschirmfoto 2020-11-10 um 22 46 44" src="https://user-images.githubusercontent.com/67914612/98737561-a681cd80-23a6-11eb-8daf-abef34e6439d.png">

## Acceptance criteria
- [ ] add the distributeButton component to the page
- [ ] write a useSpend function in the useEarnings hook.
- [ ] use the useSpend function in the useCoins component to update Graph and number-Indicators in the header.
- [ ] users must not be allowed to spend more coins than they have in their spend-account.
- [ ] users must not be able to enter negative integers (which would increase the spend-account)

## Tasks
- [ ] add the distributeButton component
- [ ] write useSpend function in useEarnings hook
- [ ] use useSpend function in the distributeButton component to use coins on spend-account
- [ ] form validation on the value in the Button-component

## Size
large
